### ISSUE TITLE
AtriumHab lighting - Tunnel

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Assets#10]
![image.png](https://images.zenhubusercontent.com/5da62a5c59191331a1f0e8c5/8e9a7182-1870-4abd-ba75-01f6e699ff28)

* The lights need some better names
* Directional background - realism in the sun is a requirement. Also it needs to be set the same for all the habs and eventually will be animated. I am choosing -55 degrees on the Y axis and -4.5 degrees on the z axis. And make it the color of the sun - almost white with a very slight yellow tint. 
* The main source of light is sunlight piped in through fiberoptic cables from collectors on the surface. Because it is delivered by such cables, they can be divided and spread out to give the best light on the interior. They can also be either area lights or point lights. But they do come with requirements - 
        * They are hot, and bright. Put them near the ceiling or somewhere they aren't easily touched by accident if they are diffuse area lights, and remember that means they will be indicated by a frosted glass and metal shaped lamp. They can also be more like point sources, in a conical metal lamp shape.
        * The goal is to make that look like sunlight.
* What is happening with the 'light from tunnel' light?

**Comment by vcvfx7** [comment]
I agree i need to change names  so they match what they do.
ok i adjusted the  Direcitonal background to Light From Tunnel  and those settings -55 in Y and  -4.5 on z  also color 

The liht from top was added  fro ma area light in top just changed names .

light from tunnel i made jsut so it makes a  small effect that light comes trough the hex  pannels  also so the transparency look transparent , if not is jsut a solid panel.

**Comment by vcvfx7** [comment]
Have to addmit top areas were so dark i am changing it now

**Comment by Moonwards** [comment]
Here are a few references for the atrium hab from the best source available - the renders done in cycles with baked lighting a couple of years ago.

![image](https://user-images.githubusercontent.com/50932660/67111898-9dbaca00-f19b-11e9-9a44-551b0b80f5f4.png)
![image](https://user-images.githubusercontent.com/50932660/67111968-c6db5a80-f19b-11e9-92b0-2ba9b7ed51a4.png)
![image](https://user-images.githubusercontent.com/50932660/67112097-0e61e680-f19c-11e9-9e30-c92772baa223.png)
![image](https://user-images.githubusercontent.com/50932660/67112149-2b96b500-f19c-11e9-9eeb-57b48b167441.png)

**Comment by vcvfx7** [comment]
Sure will keep those images.

**Comment by Moonwards** [comment]
Other notes from this morning's conversations - 
- Adding sun lights fills in everything and prevents setting up lights so they clearly come from a source. 
- There will be times a sun is needed, like in other atriums (of which there are 3 plus the long dome which is a separate challenge), and in such times, the rotation on the Z axis is left at 0, on the Y it's -4.5 degrees, and on the X, it depends on the time of day - i have chosen late afternoon,  X of -55 degrees.
- Maybe using irradiance volumes can create a sense of interior indirect light like in the references. The two areas set up during the call were a good beginning.
- You explained to me how scale in lighting works and that it needs to be set up properly. Could you add a comment about that? Just a short one as to where the settings are and maybe a link to something about it if you have one.

**Comment by vcvfx7** [comment]
* Sure sun i will add jsut 1 for  general "use"
* yup those setings were added yesterday just the x degre was not 
* irradiance seems good to solve situations  but sometimes we need or directional or sun just to "fake" lighting ( for example the light rays trough )   maybe can be trick with point willl check that 
*about scale was mainly due to the  setting i showed that it depends on light intensitiy  but is related mroe to scale  like . 10 , 1 ,  .010 and so on

**Comment by vcvfx7** [comment]
in maya you can use directional light but not as  sun there must be a way to just create that in blender so we can cast ray lights  because everything will be real time . must check that.

**Comment by Moonwards** [comment]
Where are the settings regarding scale that you mentioned?

**Comment by vcvfx7** [comment]
![settings.PNG](https://images.zenhubusercontent.com/5da734b0e252b50001ba1f06/2d0d46e6-cb55-4e2c-8bf8-e545c29b5936)

**Comment by Moonwards** [comment]
Hm. If that was changed it might affect how things are exported to Godot. It would take testing to know.

Having everything show as scale of 1 matters to how things have been set up there. I think it would be better to leave that at 1 and set up lights with the watts and such set to work with the measurements as they are.

**Comment by vcvfx7** [comment]
Yeah i will leave as they are

**Comment by Moonwards** [comment]
Wait i said the sun rotation wrong - X is 0, not Z. 

![image](https://user-images.githubusercontent.com/50932660/67121500-46275900-f1b1-11e9-97ef-ba9731cc6414.png)

**Comment by vcvfx7** [comment]
ok, but i had to change it so the light work in the atrium  if not is just dark or i had to create two and thats strange  , also i know some workflow now to add the  emizzive lamps/cylinders in the end after bake if not we have so much  exposure

this is what i mean i change sun :

**Comment by vcvfx7** [comment]
![sunn.GIF](https://images.zenhubusercontent.com/5da734b0e252b50001ba1f06/0961902c-b524-4011-aba3-7ef59de5e211)

**Comment by vcvfx7** [comment]
i ve made diferent tests and it was  getting full of brighness

**Comment by Moonwards** [comment]
I was just correcting that. I don't know that a sun can be used at all right now, but it will later.

**Comment by vcvfx7** [comment]
ok, yeah basically if i remove it there , there is no light rays coming trough.  still testing

**Comment by Moonwards** [comment]
![image](https://user-images.githubusercontent.com/50932660/67122807-42490600-f1b4-11e9-9208-4ff173241ba2.png)
![image](https://user-images.githubusercontent.com/50932660/67122994-b1bef580-f1b4-11e9-9253-d665fc4922ca.png)
Two more screenshots of an old version of this hab. Also all baked in Cycles, and quite different, but the sense of light is the same as what i'm seeking.

**Comment by vcvfx7** [comment]
yeah cyclesand eeeve is not same but i havent finnished.

**Comment by Moonwards** [comment]
This job is now finished.
