### ISSUE TITLE
Views through windows

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Assets#11]
The Hexpane windows have been adjusted so the glass looks like that of a normal window - the IOR barely matters with glass this thick, so i've set it to almost 1.

There is still the issue of what is transmitted through the glass. Blender is choosing to show the HDR because the inner sphere is too far away to be considered. 

![image.png](https://images.zenhubusercontent.com/5da62a5c59191331a1f0e8c5/98782eb0-1a8e-4366-9366-3b2301b2a8be)

That looks so bad that maybe we do need to take a different approach to HDR.
The crater is being reworked. With that set up, we could make an HDR that is set on the crater rim. It won't look really right because the location on the rim makes that impossible to set up correctly, but it would be a lot better than this.
That would make half the sphere of the HDR bright enough to work as a fill light. Maybe that's enough.

**Comment by Moonwards** [comment]
![image](https://user-images.githubusercontent.com/50932660/67055294-2f2f2b00-f10d-11e9-8d20-125d77dac7f4.png)

Putting the Screen Space Reflections > Thickness setting up to 13 helped with what it showed through the window. It is still doing an odd thing where part of the distant sphere isn't shown and instead part of the HDR is. It still seems better to resolve the HDR.

**Comment by vcvfx7** [comment]
eeeh yeah thats why i was saying and saying and saying it should be related to space but well… 
i even said about reflection probe "cubemap"  but instead  we did this method.

Normally it has to be similar or related to the enviroment so it feels and look same . even it doesnt match perfect thats why we made sphere , that can be rotated, scaed etc.

**Comment by Moonwards** [comment]
The trick there would have been to say *why* it is relevant to have the surrounding environment showing on the HDR. 

It isn't obvious that a window wouldn't show what is actually outside of it, but instead the HDR.

**Comment by vcvfx7** [comment]
Yes, thats why i tried to use the HDR with space, earth in the beginning.  :)

**Comment by vcvfx7** [comment]
i knew it was gonna show that on glass because that HDR/enviroment goes into cube map reflection, it works like that, in diferent softwares is same  Unity or Unreal.

**Comment by Moonwards** [comment]
I gave you the reasons why i wanted a different environment instead. You didn't answer any of that with any reason why it would be a problem. That would have been very helpful.

I still wouldn't want to use the crater and starry sky instead if it didn't seem like maybe the ground will provide enough fill light to be effective. I'm not sure, but it might. The light would come from underneath and that might look weird.

**Comment by Moonwards** [comment]
The same technique I suggested is actually what is currently being used in Godot.

**Comment by vcvfx7** [comment]
What does Godot has as enviroment or light?

**Comment by vcvfx7** [comment]
i explained before  about it.  I  havent tried with cráter HDR maybe we can solve it that way.
