### ISSUE TITLE
Reorganizing materials - remove all current and replace

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Assets#5]
There are many duplicate materials in the current set of models that serve no purpose. 

It may also be better for the whole material workflow to be adjusted to work best with a project meant to have many contributors but which needs to remain attractive and to keep things as simple as possible for beginner contributors.

So, should we remove all materials and then set up materials fresh, from an explanded set in the Palette file?

If so, this is how you can do that:

https://blender.stackexchange.com/a/7161/7548

**Comment by vcvfx7** [comment]
I followe similar concep and , jst checking wich is used and unused are gone by select linked ( object) from materials slot .
Then i jsut change names

**Comment by Moonwards** [comment]
I don't know what you mean by select linked. I don't see that option

Deleting materials in orphan data isn't going to help much here. Most materials are copies created by processes like appending and duplicating objects. They have a user but still shouldn't exist.

The solution in the link in my posting before is more radical. It is a way to remove ALL materials from EVERYTHING. 

That is probably still a faster and better way to handle this. Get rid of them all, make some nice materials in the Palette file, and then append the palette in its own collection, and start adding materials to things - so things look nice, not necessarily so they are the same as before.

**Comment by Moonwards** [comment]
Ok - i did find the select linked menu item - in the pop-up menu on right click of a material in the Blender file view. So far i'm finding it rather hard to work with.

**Comment by vcvfx7** [comment]
You need to change  here :

**Comment by vcvfx7** [comment]
https://gyazo.com/519d7a2d0ffccb73335daaeda9805b67

**Comment by vcvfx7** [comment]
so you can see the modeling tab and options come on the file . There i should  unink materials first and ddelete then do what you mention  append from the color palete  and Work agai nthe materials .

**Comment by vcvfx7** [comment]
i Will follow that as the link you mentionwith the materials addon , just give me a sec so i check

**Comment by vcvfx7** [comment]
bledner 2.8 dont have the option maybe in 2.8 is only posible with blender file browser

**Comment by vcvfx7** [comment]
![marterial](https://user-images.githubusercontent.com/52358220/66787971-55559080-eeab-11e9-8420-64ce0b810637.PNG)

**Comment by Moonwards** [comment]
I don't know what that command does, but when i search for it with all objects selected in a test file, it doesn't show up. Also i don't know if deleting material nodes is what we want to do.

![mat](https://user-images.githubusercontent.com/50932660/66788261-9b5f2400-eeac-11e9-8e66-8a5ddabc7617.jpg)

Doing it that way is just as fast. Click on that menu item and all materials will disappear. Then reload the file and they will be gone forever.

Then if you append the Object Palette-64Color from the file Models / Materials / Palette-64color.blend, all the materials will be back again. 
So if that palette is updated, perhaps in a series of grids like that, then we could set up a complete material system that is easily maintained.

**Comment by vcvfx7** [comment]
Will delete materials then as that popup (  i did and it didnt work at all  )and append color palete tomorrow as you mention here.
I just push the file a momento ago.
What i dont see clear is if we delete materials from scene , how we Will add material  to objects  after delete?

**Comment by Moonwards** [comment]
You are referring to the fact the material slots are also deleted by this process, and so if an object combines several materials, the faces for each have to be selected again so that each material can be put in the right place?

Yes, that is a problem.

**Comment by vcvfx7** [comment]
yup,  i Will check  or find a solution because if not is redo a loot again, tomorrow i ll doublé check best option.

**Comment by vcvfx7** [comment]
I was thinking maybe best  solution would be : 
1) continue importing our omd materials and make modifications as we talked 
2) once imported made or run a file browser and delete  those  materials wich are not applied ( this is risky and must be done carefull so we dont lost good materials )
3) once we review jsut leave current optimised and the  append from color palette  and jsut there make a quick comparision and leave color palete  and modified or delete modified and apply  this to the appened from color palter so thne we have 1 material.

Sounds a bit complicated but it i  must be  carefully so we dont lose anything on the momento we append and delete and clean

**Comment by Moonwards** [comment]
I suppose that will have to be the way. It is annoying how all those old materials make it hard to go through the list.

Maybe it would be a good idea to add the number 1 to the front of new material names, in order to force them to the top of the material list so you don't have to scroll. Like this "1-Cheese".

**Comment by vcvfx7** [comment]
Maybe the material cleaning is the last thing we do after  all materials are aproved

**Comment by Moonwards** [comment]
If you don't find it hard to work with all those obsolete materials in the list, then sure, it can be left. I really think most of them could be deleted right now and it would make no difference at all. It is easy enough to see which ones are duplicates of the same thing.

I have talked about naming according to place. I opened an issue about that, go to that issue to see it - issue #6

**Comment by vcvfx7** [comment]
Its not so hard because you dont see the material unless you work on it we can leave and dleelte i nthe end and use that naming as issue#6

**Comment by vcvfx7** [comment]
hELLO
