### ISSUE TITLE
Material naming and palette organization

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Assets#6]
If materials have been set up for an object in some way that makes it unusable on any other object then the materials for that object should include the object name. So, basically where an image texture is being used on a UV map. 

We should create a set of materials that are designed to be reused in many places, and only use ones that are specific to an object when something makes that necessary.

For instance, the color topaz could be used in a set of shaders imitating different materials - topaz matte ceramic, topaz glossy enamel, topaz metal clearcoat.

Where procedural textures are stretches on some axes, include in the name the axis or axes where it can be used on the end of the name.

**Comment by vcvfx7** [comment]
Oh this is Good to know seems i will need to rename son anyway , i am just testing the look. But sounds Good to have that  naming.

**Comment by Moonwards** [comment]
I am revising the rules in the first post to include more detail.

**Comment by vcvfx7** [comment]
sure
