### ISSUE TITLE
Review if objects depend on UVs and if necesary  unrwap objects so we can use any kind of shader/material

### ISSUE THREAD

**Issue by vcvfx7** [moonwards1/Moonwards-Assets#8]

**Comment by Moonwards** [comment]
Ok, so the conclusion based on discussion on the Discord #dev channel is that UV maps are used in Godot and should be properly made in Blender.

I am going to close this and open a new issue that lists the task of unwrapping all objects properly

**Comment by vcvfx7** [comment]
Sure, thats fine
