### ISSUE TITLE
UV unwrap all objects in AtriumHab properly

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Assets#9]
The AtriumHab has objects that were never UV unwrapped because they used only a simple material and it was not deemed necessary. In making proper materials for everything, all objects need to be unwrapped well.

*Edit*
Materials for this project will largely be simple PBR materials, some of which have a simple procedural element (that might later be turned into image textures, depending on performance requirements). See materials discussion, #16.

So, generally things can be unwrapped with smart uv project. 
Where objects have more detail and smart uv project isn't working well enough, the workflow is as follows:

1. Select an area that makes a good uv island. 
      - A good tactic with bevelled edges is to select the main faces, then press `ctrl +` to expand the selected area to the best point

![image](https://user-images.githubusercontent.com/50932660/67538112-b0edfe00-f6a3-11e9-8564-9dea8f76d7c6.png)

2. press `u > Unwrap`
    
![image](https://user-images.githubusercontent.com/50932660/67538625-4473fe80-f6a5-11e9-9db4-414bcdd584d5.png)

3. Move the island off the grid area for now 

![image](https://user-images.githubusercontent.com/50932660/67538674-6d948f00-f6a5-11e9-8763-49ba3238e5d8.png)

4. Choose another area to be a uv island. More than one such area can be set up as long as the areas don't touch anywhere.

![image](https://user-images.githubusercontent.com/50932660/67538909-25c23780-f6a6-11e9-8cd8-c0358f8c311d.png)

![image](https://user-images.githubusercontent.com/50932660/67539017-82255700-f6a6-11e9-9b7b-c135dea601bf.png)

5. Do this for the whole object. Be aware of useful tools, such as the UV Sync Selection button to the right of the Editor type selector button. 
![image](https://user-images.githubusercontent.com/50932660/67540023-93239780-f6a9-11e9-9771-acad65e7ea3c.png)

![image](https://user-images.githubusercontent.com/50932660/67539605-44293280-f6a8-11e9-92eb-66c5207636ad.png)

6. Arrange the islands into a square and scale to fit in the UV grid. With these kinds of materials, rotating islands is fine. Shrink hidden areas to best use UV map real estate.

![image](https://user-images.githubusercontent.com/50932660/67539880-27412f00-f6a9-11e9-9ee0-5383e7a050ec.png)

With this approach, the scale of all faces is roughly preserved. If desired, as a final step, seams can be places around all the islands in one step

![image](https://user-images.githubusercontent.com/50932660/67539965-68d1da00-f6a9-11e9-8e98-201da56c6a2a.png)

And `Minimize Stretch` might be desirable

![image](https://user-images.githubusercontent.com/50932660/67540290-789dee00-f6aa-11e9-960a-1da025115ef4.png)

**Comment by vcvfx7** [comment]
Sure, sometimes automatic unwraping makes it faster or jsut some  details manuallly
